workflows:
  android-build:
    name: Android APK Build

    environment:
      java: 17

    scripts:
      - name: Check current directory
        script: pwd

      - name: List all files
        script: ls -R

      - name: Make gradlew executable
        script: chmod +x gradlew

      - name: Run Gradle Build
        script: ./gradlew clean assembleDebug --info

    artifacts:
      - app/build/outputs/**/*.apk
