workflows:
  android-build:
    name: Android APK Build

    environment:
      java: 17
      android_signing:
        - default

    scripts:
      - name: Set up Android SDK
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Make gradlew executable
        script: chmod +x gradlew

      - name: Build APK
        script: ./gradlew clean assembleDebug --stacktrace

    artifacts:
      - app/build/outputs/apk/debug/*.apk
