name: Test Build Debug

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          
      - uses: android-actions/setup-android@v3
      
      - run: chmod +x gradlew
      
      - name: Clean and Build
        run: |
          ./gradlew clean
          ./gradlew :app:assembleDebug --info || true
          
      - name: Upload whatever exists
        uses: actions/upload-artifact@v4
        with:
          name: all-outputs
          path: app/build/outputs/
          if-no-files-found: ignore
          
