name: Android CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Give gradlew permission
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew clean assembleDebug

      - name: Show APK folder
        run: |
          echo "Listing APK outputs"
          ls -R app/build/outputs || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: app/build/outputs/
