name: Android Build APK

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Give permission
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Show build folder
        run: ls -R app/build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: translator-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: warn
