name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # 🔥 IMPORTANT: Android SDK install
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Give permission to gradlew
      run: chmod +x gradlew

    - name: Build APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Show APK files
      run: ls -R app/build/outputs/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-app-apk
        path: app/build/outputs/apk/debug/*.apk
