name: Android Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Give permission to gradlew
      run: chmod +x gradlew

    - name: Clean project
      run: ./gradlew clean

    - name: Build APK (IMPORTANT)
      run: ./gradlew assembleDebug --stacktrace

    - name: Check APK folder
      run: ls -R app/build/outputs/apk/

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk-file
        path: app/build/outputs/apk/debug/*.apk
